Traceback (most recent call last):
  File "/well/win-fmrib-analysis/users/gqu790/moval/moval_scripts/eval_seg3d_brainlesion.py", line 269, in <module>
    main()
  File "/well/win-fmrib-analysis/users/gqu790/moval/moval_scripts/eval_seg3d_brainlesion.py", line 215, in main
    logit_cls = np.stack((logit_cls0, logit_cls1))  # ``(d, H, W, D)``
  File "<__array_function__ internals>", line 200, in stack
  File "/well/win-fmrib-analysis/users/gqu790/conda/skylake/envs/moval/lib/python3.8/site-packages/numpy/core/shape_base.py", line 471, in stack
    return _nx.concatenate(expanded_arrays, axis=axis, out=out,
  File "<__array_function__ internals>", line 200, in concatenate
numpy.core._exceptions.MemoryError: Unable to allocate 132. MiB for an array with shape (2, 197, 233, 189) and data type float64
